{% set name = "ab12phylo" %}
{% set version = "0.5.19b0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b27f7f6824a4e80d8e6190c86d19214c1465c34678ca0f2f4ee3580c6314ff7b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - ab12phylo = ab12phylo.ab12phylo_app:main
    - ab12phylo-init = ab12phylo.ab12phylo_init:main
    - ab12phylo-cmd = ab12phylo_cmd.main:_main
    - ab12phylo-visualize = ab12phylo_cmd.phylo:_visualize
    - ab12phylo-view = ab12phylo_cmd.phylo:_view
    - ab12phylo-add-xml = ab12phylo_cmd.blast:_add_xml

requirements:
  host:
    - pip
    - python
  build:
    - python
  run:
    - python
    - biopython
    - pyyaml
    - jinja2
    - lxml
    - xmltramp2
    - toyplot
    - toytree <=1.2.0
    - numpy
    - pandas
    - matplotlib
    - svgutils
    - pillow
    - requests
    - beautifulsoup4
    - pygobject
    - gtk3
    - hicolor-icon-theme
    - adwaita-icon-theme

test:
  imports:
    - ab12phylo
    - ab12phylo_cmd

about:
  license: GPL-3.0
  summary: "Integrated pipeline for ML phylogenetic inference from ABI trace and FASTA data"

extra:
  recipe-maintainers:
    - lkndl
